### ISSUE TITLE
Parse other syntaxes?

### ISSUE THREAD

**Issue by eimajenthat** [IcecaveStudios/duct#12]
This is a really cool library, and poking around, you seem to have abstracted things very elegantly.  What would it take to make this library parse other syntaxes, besides JSON, maybe Yaml, XML, or SQL?

I have a case where I want to parse a large SQL file (a SQL dump), and isolate and execute each SQL query individually, but I don't want to load the whole file thing into memory, so I was thinking of using a file stream to open the file, and read it one query at a time.  However, I've had a little trouble figuring out how to do that.  Then I stumbled across duct, and it occurred to me this might be 80% to 90% of what I need.

I see the Lexer class, which which looks like the place to start, but I'm still trying to wrap my brain around how this works.  Any tips would be much appreciated.  And if I can get a SQL parser working, I'd be happy to contribute it back here, or as a separate open source project, whichever you prefer.

**Comment by jmalloc** [comment]
Thanks for your interest :) 

It doesn't seem that there's very much code that could be retained while parsing other formats, and as such I would prefer to keep Duct focused solely on JSON, though streaming parsers for similar structural formats (such as YAML) could share a similar project structure and a common interface. I would also be inclined to parse a language such as SQL quite differently, as you'd likely want to produce an [abstract syntax tree](http://en.wikipedia.org/wiki/Abstract_syntax_tree) that represents the query, rather than plain PHP values. It might also be better to use a [parser generator](http://en.wikipedia.org/wiki/Compiler-compiler) for a grammar as complex as SQL.

In regards to your use case, you might try https://github.com/soundintheory/php-sql-parser. I don't *think* it accepts streaming input, but you might be able to do something simple such as reading the file until a semicolon is encountered, and then running that entire buffer through the parser to validate the query.  This would let you isolate individual queries without reading the file in its entirety, though I will admit it's not quite as elegant is having a proper streaming parser.

If you *do* wan't to attempt a proper streaming parser by hand you're probably right that the lexer is the place to start. I'll describe how the Duct lexer works. I'm not sure how familiar you are with parsers in general, so forgive me if I'm explaining things you already know. Also, I am by no means an expert!

**Lexer**

The lexer is responsible for converting input from a string of characters into a sequence of [`Token`](https://github.com/IcecaveStudios/duct/blob/develop/src/Detail/Token.php) objects.  You can see the various token types used by Duct in the [`TokenType` enumeration](https://github.com/IcecaveStudios/duct/blob/develop/src/Detail/TokenType.php).

For example the input `[ 1, 2 ]` would result in a token sequence that looks something like:

`bracket-open number-literal(1) comma number-literal(2) bracket-close`

This particular lexer is implemented as a hand-rolled state machine. Incoming character data is passed to `feed()` as it becomes available.  The parser transitions its internal state such that future calls to `feed()` can pick up where it left off. Every time that a full token is recognised it is "emitted" by invoking a callback with the token as a parameter. Lastly the `finalize()` method is called to clean up the last of the input and throw any errors that may occur due to the stream being cut-off mid-token (for example in the middle of a JSON string).

Note that the lexer has no structural information and will happily produce a sequence of tokens that do not represent a valid JSON document.

**TokenStreamParser**

`TokenStreamParser` accepts tokens as input (via the callback invoked by the lexer) and is responsible for recognising valid sequences and throwing exceptions when an invalid sequence is encountered (ie, a JSON syntax error). It emits events as each structural element is encountered. For example, the events emitted for the example `[ 1, 2 ]` would be something like `array-open value(1) value(2) array-close`.

**EventedParser**

This is a facade that ties `Lexer` and the `TokenStreamParser` together to provide a nice interface that accepts character data as input and emits events. In addition to the events emitted by `TokenStreamParser`, it also adds `document-open` and `document-close` events.

**Parser**

This parser also ties `Lexer` and `TokenStreamParser` together, but instead of producing events it builds a nested PHP object/array structure that represents the input, similar to the output of `json_decode()`.  The parsed values are retrieved by calling the `values()` method.

This got a bit longer than I had expected, hopefully it provides enough info to get started if you do decide to have a play around with a parser :)

**Comment by eimajenthat** [comment]
Thanks so much for this!  I'm still digesting it, but I think it's going to be a huge help.
